### ISSUE TITLE
how to install the dependency SavjeeCoin to node_modules?

### ISSUE THREAD

**Issue by rxxy** [Savjee/savjeecoin-frontend#3]
I try run `npm start` got this error:
 `Cannot find module 'SavjeeCoin/src/blockchain`

**Comment by Savjee** [comment]
Thanks for reporting this! However, I get a different error:

```
ERROR in ./node_modules/SavjeeCoin/src/blockchain.js
Module not found: Error: Can't resolve 'crypto' in '/Users/xavier/Desktop/savjeecoin-frontend/node_modules/SavjeeCoin/src'
```

This is probably related to the fact that we changed SavjeeCoin quite a bit. It's now more tightly integrated with some node.js modules that don't run in the browser.

For now, I have pinned the SavjeeCoin dependency to an older commit. Not the prettiest solution but it should work now.

**Comment by rxxy** [comment]
It works. very good. Thank you

**Comment by harshwardhanedu** [comment]
npm install --save github:Savjee/SavjeeCoin

not working

**Comment by Savjee** [comment]
@harshwardhanedu You're mentioning SavjeeCoin, but this is the repository for savjeecoin-frontend.
If you want to install SavjeeCoin, check out the [README](https://github.com/Savjee/SavjeeCoin) on the GitHub page. The NPM command is:

```
npm install --save savjeecoin
```

**Comment by harshwardhanedu** [comment]
> @harshwardhanedu You're mentioning SavjeeCoin, but this is the repository for savjeecoin-frontend. If you want to install SavjeeCoin, check out the [README](https://github.com/Savjee/SavjeeCoin) on the GitHub page. The NPM command is:
> 
> ```
> npm install --save savjeecoin
> ```

Actully i have done till 4th video . leter on i am creating frontend using your 5th video so you have mentioned in video to go through this command to include dependencies in frontent

**Comment by DonfackPAvel** [comment]
error on errors
  has no default export.

4 import EC from "elliptic";
can solve this problem
