### ISSUE TITLE
"Job name "getProjectMetadata" does not exist"

### ISSUE THREAD

**Issue by itsGizem** [Savjee/savjeecoin-frontend#8]
hey there savjee,

i am trying to run the frontent code and after following the instructions and doin npm install, i cant run the code. Whenever i do npm start, it tells me that i have to use ng serve. I do that and i get an error message as stated in the title.
i have included 2 screenshots aswell. Hope there will be a solution to this.

Have a good day

![error1](https://user-images.githubusercontent.com/38055439/88372702-ba250c00-cd96-11ea-8e35-f3ea5fb7d45f.png)
![error2](https://user-images.githubusercontent.com/38055439/88372703-babda280-cd96-11ea-9a20-339249fea84b.png)

**Comment by masonwilliams6** [comment]
@itsGizem This error occurred for me when `npm audit fix` was ran on the project. I would recommend not runing that command and only running `npm install`.
